# Generated by Django 3.0.1 on 2020-01-05 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_question_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='created_by',
            field=models.IntegerField(null=True),
        ),
    ]
