# Generated by Django 3.0.1 on 2020-01-05 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_reviews'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='question_id',
            new_name='questions_id',
        ),
    ]
